name = "cShiftedArrays"
uuid = "afc28532-05cf-429b-8852-6ba2afc35909"
repo = "https://github.com/DEEPDIP-project/cShiftedArrays.jl.git"
version = "2.0.0"

[compat]
julia = "1.5"

[extras]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "AbstractFFTs"]
